# Generated by Django 5.2.8 on 2025-11-23 05:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the encrypted file', max_length=500, unique=True)),
                ('original_name', models.CharField(help_text='Original filename before encryption', max_length=255)),
                ('file_hash', models.CharField(help_text='SHA-256 hash of the original file', max_length=64)),
                ('size', models.BigIntegerField(help_text='Size of the encrypted file in bytes')),
                ('encryption_backend', models.CharField(default='fernet', help_text='Encryption backend used', max_length=50)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the file was uploaded')),
                ('model_name', models.CharField(blank=True, help_text='Django model this file belongs to', max_length=100, null=True)),
                ('model_pk', models.CharField(blank=True, help_text='Primary key of the model instance', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this file is still active')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='When the file was marked as deleted', null=True)),
            ],
            options={
                'verbose_name': 'File Metadata',
                'verbose_name_plural': 'File Metadata',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['file_path'], name='storage_fil_file_pa_0bda02_idx'), models.Index(fields=['file_hash'], name='storage_fil_file_ha_9e2030_idx'), models.Index(fields=['uploaded_at'], name='storage_fil_uploade_b4d496_idx'), models.Index(fields=['model_name', 'model_pk'], name='storage_fil_model_n_6a297c_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('file_path', models.CharField(help_text='Path to the file', max_length=500)),
                ('action', models.CharField(choices=[('upload', 'File Upload'), ('download', 'File Download'), ('download_via_signed_url', 'Download via Signed URL'), ('decrypt', 'File Decryption'), ('delete', 'File Deletion'), ('generate_url', 'Generate Signed URL'), ('access_denied', 'Access Denied'), ('validation_failed', 'Validation Failed')], help_text='Type of action performed', max_length=30)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string', null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('denied', 'Denied')], default='success', help_text='Status of the operation', max_length=10)),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata about the operation')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='file_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Access Log',
                'verbose_name_plural': 'File Access Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='storage_fil_timesta_8d0a37_idx'), models.Index(fields=['file_path'], name='storage_fil_file_pa_ee87d4_idx'), models.Index(fields=['user'], name='storage_fil_user_id_e75151_idx'), models.Index(fields=['action'], name='storage_fil_action_33d862_idx'), models.Index(fields=['ip_address'], name='storage_fil_ip_addr_760cc9_idx')],
            },
        ),
        migrations.CreateModel(
            name='FileValidationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the validation occurred')),
                ('filename', models.CharField(help_text='Name of the file being validated', max_length=255)),
                ('validation_type', models.CharField(choices=[('size', 'File Size'), ('extension', 'File Extension'), ('mime', 'MIME Type'), ('dangerous', 'Dangerous File Check'), ('content', 'Content Validation')], help_text='Type of validation performed', max_length=20)),
                ('passed', models.BooleanField(help_text='Whether the validation passed')),
                ('detected_value', models.CharField(blank=True, help_text='What was detected (e.g., MIME type, file size)', max_length=255, null=True)),
                ('expected_value', models.CharField(blank=True, help_text='What was expected', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Detailed error message', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the upload request', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='User who uploaded the file', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'File Validation Log',
                'verbose_name_plural': 'File Validation Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='storage_fil_timesta_95efc2_idx'), models.Index(fields=['validation_type'], name='storage_fil_validat_335d82_idx'), models.Index(fields=['passed'], name='storage_fil_passed_3c0690_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignedURLLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the signed URL was created')),
                ('file_path', models.CharField(help_text='Path to the file', max_length=500)),
                ('expires_at', models.DateTimeField(help_text='When the URL expires')),
                ('created_for_ip', models.GenericIPAddressField(blank=True, help_text='IP address the URL was created for (if IP-bound)', null=True)),
                ('permissions', models.JSONField(default=list, help_text='Permissions granted by this URL')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this URL was used')),
                ('last_used_at', models.DateTimeField(blank=True, help_text='When the URL was last used', null=True)),
                ('last_used_by_ip', models.GenericIPAddressField(blank=True, help_text='IP address that last used this URL', null=True)),
                ('revoked', models.BooleanField(default=False, help_text='Whether this URL has been revoked')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When the URL was revoked', null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the signed URL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_signed_urls', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='User who revoked the URL', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_signed_urls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signed URL Log',
                'verbose_name_plural': 'Signed URL Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='storage_sig_created_ae4e97_idx'), models.Index(fields=['expires_at'], name='storage_sig_expires_cd1ac1_idx'), models.Index(fields=['file_path'], name='storage_sig_file_pa_e584cb_idx'), models.Index(fields=['created_by'], name='storage_sig_created_7ae438_idx')],
            },
        ),
    ]
