"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# TODO: Eliminar estos secretos de acá, sería un blooper tenerlos en las presentación
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())


# Application definition

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Third-party security apps
    "axes",  # Brute force protection
    "django_otp",  # OTP framework
    "django_otp.plugins.otp_totp",  # TOTP (Google Authenticator, etc.)
    "django_otp.plugins.otp_static",  # Backup codes
    # TODO: Algo pro sería añadirle OTP de whatsapp a la librería
    # Our custom security features
    "auth_security",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",
    "auth_security.middleware.SessionSecurityMiddleware",
    "django_otp.middleware.OTPMiddleware",  # django-otp MFA support
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES: list[dict[str, object]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES: dict[str, dict[str, object]] = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, object]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "auth_security.authentication.password_validators.ComplexityValidator",
        "OPTIONS": {
            "min_uppercase": 1,
            "min_lowercase": 1,
            "min_digits": 1,
            "min_special": 1,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.BreachedPasswordValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.PasswordReuseValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.ForbiddenSubstringValidator",
        "OPTIONS": {
            "forbidden_list": [
                "company",
                "name",
                "xpendit",
            ],  # Add your own forbidden words
            "similarity_threshold": 0.8,  # 80% similarity threshold
            "case_sensitive": False,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 3600  # 1 hour

# CSRF Protection
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Strict"


# Caching (required for rate limiting and lockout tracking)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# =============================================================================
# DJANGO-AXES CONFIGURATION (Brute Force Protection)
# =============================================================================

# Authentication backend for axes
AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend
    "axes.backends.AxesStandaloneBackend",
    # Django ModelBackend is the default authentication backend
    "django.contrib.auth.backends.ModelBackend",
]

# Axes Configuration
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Cooloff period in hours (can also use timedelta)
AXES_RESET_ON_SUCCESS = True  # Reset failures on successful login
AXES_LOCKOUT_TEMPLATE = None  # Use default lockout response
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # Lock by username and IP
AXES_IPWARE_PROXY_COUNT = 1  # Number of proxies (adjust for your setup)
AXES_VERBOSE = True  # Enable verbose logging
AXES_ENABLE_ADMIN = True  # Enable axes admin interface
# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================

# Redis Configuration (optional, for rate limiting)
REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/0")

# Django Security Configuration
DJANGO_SEC = {
    # Risk profile: 'strict', 'moderate', 'relaxed'
    "RISK_PROFILE": config("SECURITY_RISK_PROFILE", default="moderate"),
    # Enable/disable security features
    "ENABLE_SECURITY_HEADERS": config(
        "ENABLE_SECURITY_HEADERS", default=True, cast=bool
    ),
    "ENABLE_RATE_LIMITING": config("ENABLE_RATE_LIMITING", default=True, cast=bool),
    "ENABLE_REQUEST_SIZE_LIMIT": config(
        "ENABLE_REQUEST_SIZE_LIMIT", default=True, cast=bool
    ),
    "ENABLE_SUSPICIOUS_PATTERNS": config(
        "ENABLE_SUSPICIOUS_PATTERNS", default=True, cast=bool
    ),
    # CSP Policy configuration
    "CSP_POLICY": "moderate",  # 'strict', 'moderate', 'relaxed', 'custom'
    "CSP_REPORT_ONLY": DEBUG,  # Report-only mode in development
    # Rate limiting configuration
    "RATE_LIMITING": {
        "BACKEND": "cache",  # 'redis', 'cache', 'memory'
        "DEFAULT_LIMITS": {
            "anonymous": "100/h",
            "authenticated": "1000/h",
        },
        "ENDPOINT_LIMITS": {
            "/api/login/": "5/m",
            "/api/register/": "10/h",
            "/api/password-reset/": "3/h",
        },
    },
    # Request size limits
    "REQUEST_SIZE_LIMIT": 10 * 1024 * 1024,  # 10 MB default
    "REQUEST_SIZE_LIMITS": {
        "/api/upload/": 100 * 1024 * 1024,  # 100 MB for uploads
    },
    # Suspicious patterns action: 'log', 'block', 'degrade'
    # Set to 'block' to test security features even in development
    "SUSPICIOUS_ACTION": config("SUSPICIOUS_ACTION", default="block"),
    "SUSPICIOUS_THRESHOLD": 5,  # Auto-block after N violations
    "BLOCK_DURATION": 3600,  # 1 hour,
    # Authentication Protection
    "AUTH_PROTECTION": {
        "MAX_LOGIN_ATTEMPTS": 5,
        "LOCKOUT_DURATION": 900,  # 15 minutes in seconds
        "LOCKOUT_STRATEGY": "exponential",  # fixed, exponential
        "DELAY_STRATEGY": "exponential",  # none, fixed, exponential
        "BASE_DELAY_SECONDS": 1,
        "NOTIFICATION": {
            "EMAIL_ON_LOCKOUT": True,
            "EMAIL_ON_SUSPICIOUS_LOGIN": True,
            "WEBHOOK_URL": None,
        },
    },
    # Session Security
    "SESSION_SECURITY": {
        "ABSOLUTE_TIMEOUT": 28800,  # 8 hours max session
        "INACTIVITY_TIMEOUT": 3600,  # 1 hour inactivity timeout
        "ROTATE_ON_LOGIN": True,  # Prevent session fixation
        "BIND_TO_IP": True,  # Validate IP doesn't change
        "BIND_TO_USER_AGENT": False,  # Can cause issues with browser updates
    },
    # Password Validation
    "PASSWORD_VALIDATORS": {
        "MIN_LENGTH": 12,
        "COMPLEXITY": {
            "min_uppercase": 1,
            "min_lowercase": 1,
            "min_digits": 1,
            "min_special": 1,
        },
        "CHECK_BREACHED": True,
        "PREVENT_REUSE": 5,
        "FORBIDDEN_SUBSTRINGS": [
            "company",
            "name",
            "xpendit",
        ],
    },
}

# Apply secure defaults based on environment
from app.security.conf import apply_secure_defaults  # noqa: E402

# Use relaxed preset for development, moderate for production
if DEBUG:
    apply_secure_defaults(globals(), preset="relaxed")
else:
    apply_secure_defaults(globals(), preset=DJANGO_SEC["RISK_PROFILE"])

# The apply_secure_defaults function will automatically add our security middleware
# to the MIDDLEWARE list, so no manual modification needed there
