"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

from decouple import Csv, config
import re

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# TODO: Eliminar estos secretos de acá, sería un blooper tenerlos en las presentación
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config(
    "SECRET_KEY",
    default="django-insecure-dev-key-only-for-development-not-for-production-use-this-key-is-not-secure",
)
DEBUG = config("DEBUG", default=False, cast=bool)

ALLOWED_HOSTS = config("ALLOWED_HOSTS", default="localhost,127.0.0.1", cast=Csv())

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = config("CSRF_TRUSTED_ORIGINS", default="", cast=Csv())


# Application definition

INSTALLED_APPS: list[str] = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    # Third-party security apps
    "axes",  # Brute force protection
    "django_otp",  # OTP framework
    "django_otp.plugins.otp_totp",  # TOTP (Google Authenticator, etc.)
    "django_otp.plugins.otp_static",  # Backup codes
    "django_crypto_fields",  # Battle-tested encryption library
    # TODO: Algo pro sería añadirle OTP de whatsapp a la librería
    # Our custom security features
    "auth_security",
    "input_validation",  # Input validation and sanitization
    "data_protection",  # Cryptographic controls and encrypted fields (ISO27001 A.10.1)
    "auditory",
    "app.security",
    "app.security.storage",
]

MIDDLEWARE: list[str] = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "auditory.http.HTTPProtectionMiddleware",
    "auditory.audit.middleware.AuditContextMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "axes.middleware.AxesMiddleware",
    "auth_security.middleware.SessionSecurityMiddleware",
    "django_otp.middleware.OTPMiddleware",  # django-otp MFA support
    "auditory.audit.user_context.UserContextEnricher",
    "auditory.api.middleware.APIRequestLoggingMiddleware",  # NEW: API request logging
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "app.urls"

TEMPLATES: list[dict[str, object]] = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "app.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Parse DATABASE_URL from environment
DATABASE_URL = config("DATABASE_URL", default="")

match_obj = re.match(
    r'postgresql://(?P<user>[^:]+):(?P<password>[^@]+)@(?P<host>[^/]+)/(?P<name>[^?]+)(\?.*)?',
    DATABASE_URL
)
if not DATABASE_URL or not match_obj:
    raise ValueError("Invalid DATABASE_URL format")

db_config = match_obj.groupdict() if match_obj else {}
DATABASES: dict[str, dict[str, object]] = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": db_config["name"],
        "USER": db_config["user"],
        "PASSWORD": db_config["password"],
        "HOST": db_config["host"],
        "PORT": "5432",
        "OPTIONS": {
            "sslmode": "require",
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS: list[dict[str, object]] = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.MinimumLengthValidator",
        "OPTIONS": {"min_length": 12},
    },
    {
        "NAME": "auth_security.authentication.password_validators.ComplexityValidator",
        "OPTIONS": {
            "min_uppercase": 1,
            "min_lowercase": 1,
            "min_digits": 1,
            "min_special": 1,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.BreachedPasswordValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.PasswordReuseValidator",
    },
    {
        "NAME": "auth_security.authentication.password_validators.ForbiddenSubstringValidator",
        "OPTIONS": {
            "forbidden_list": [
                "company",
                "name",
                "xpendit",
            ],  # Add your own forbidden words
            "similarity_threshold": 0.8,  # 80% similarity threshold
            "case_sensitive": False,
        },
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =============================================================================
# SECURITY CONFIGURATION
# =============================================================================

# Session Security
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_COOKIE_SAMESITE = "Lax"
SESSION_COOKIE_AGE = 3600  # 1 hour

# CSRF Protection
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = True
CSRF_COOKIE_SAMESITE = "Strict"


# Caching (required for rate limiting and lockout tracking)
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}

# =============================================================================
# DJANGO-AXES CONFIGURATION (Brute Force Protection)
# =============================================================================

# Authentication backend for axes
AUTHENTICATION_BACKENDS = [
    # AxesStandaloneBackend should be the first backend
    "axes.backends.AxesStandaloneBackend",
    # Django ModelBackend is the default authentication backend
    "django.contrib.auth.backends.ModelBackend",
]

# Axes Configuration
AXES_FAILURE_LIMIT = 5  # Lock after 5 failed attempts
AXES_COOLOFF_TIME = 1  # Cooloff period in hours (can also use timedelta)
AXES_RESET_ON_SUCCESS = True  # Reset failures on successful login
AXES_LOCKOUT_TEMPLATE = None  # Use default lockout response
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]  # Lock by username and IP
AXES_IPWARE_PROXY_COUNT = 1  # Number of proxies (adjust for your setup)
AXES_VERBOSE = True  # Enable verbose logging
AXES_ENABLE_ADMIN = True  # Enable axes admin interface



# ============================================================================
# SECURITY CONFIGURATION
# ============================================================================

# Redis Configuration (optional, for rate limiting)
REDIS_URL = config("REDIS_URL", default="redis://localhost:6379/0")

# Django Security Configuration
DJANGO_SEC = {
    # Risk profile: 'strict', 'moderate', 'relaxed'
    "RISK_PROFILE": config("SECURITY_RISK_PROFILE", default="moderate"),
    # Enable/disable security features
    "ENABLE_SECURITY_HEADERS": config(
        "ENABLE_SECURITY_HEADERS", default=True, cast=bool
    ),
    "ENABLE_RATE_LIMITING": config("ENABLE_RATE_LIMITING", default=True, cast=bool),
    "ENABLE_REQUEST_SIZE_LIMIT": config(
        "ENABLE_REQUEST_SIZE_LIMIT", default=True, cast=bool
    ),
    "ENABLE_SUSPICIOUS_PATTERNS": config(
        "ENABLE_SUSPICIOUS_PATTERNS", default=True, cast=bool
    ),
    # CSP Policy configuration
    "CSP_POLICY": "moderate",  # 'strict', 'moderate', 'relaxed', 'custom'
    "CSP_REPORT_ONLY": DEBUG,  # Report-only mode in development
    # Rate limiting configuration
    "RATE_LIMITING": {
        "BACKEND": "cache",  # 'redis', 'cache', 'memory'
        "DEFAULT_LIMITS": {
            "anonymous": "5/m",
            "authenticated": "1000/h",
        },
        "ENDPOINT_LIMITS": {
            "/api/login/": "5/m",
            "/api/register/": "10/h",
            "/api/password-reset/": "3/h",
        },
    },
    # Request size limits
    "REQUEST_SIZE_LIMIT": 10 * 1024 * 1024,  # 10 MB default
    "REQUEST_SIZE_LIMITS": {
        "/api/upload/": 100 * 1024 * 1024,  # 100 MB for uploads
    },
    # Suspicious patterns action: 'log', 'block', 'degrade'
    # Set to 'block' to test security features even in development
    "SUSPICIOUS_ACTION": config("SUSPICIOUS_ACTION", default="block"),
    "SUSPICIOUS_THRESHOLD": 5,  # Auto-block after N violations
    "BLOCK_DURATION": 3600,  # 1 hour,
    # Authentication Protection
    "AUTH_PROTECTION": {
        "MAX_LOGIN_ATTEMPTS": 5,
        "LOCKOUT_DURATION": 900,  # 15 minutes in seconds
        "LOCKOUT_STRATEGY": "exponential",  # fixed, exponential
        "DELAY_STRATEGY": "exponential",  # none, fixed, exponential
        "BASE_DELAY_SECONDS": 1,
        "NOTIFICATION": {
            "EMAIL_ON_LOCKOUT": True,
            "EMAIL_ON_SUSPICIOUS_LOGIN": True,
            "WEBHOOK_URL": None,
        },
    },
    # Session Security
    "SESSION_SECURITY": {
        "ABSOLUTE_TIMEOUT": 28800,  # 8 hours max session
        "INACTIVITY_TIMEOUT": 3600,  # 1 hour inactivity timeout
        "ROTATE_ON_LOGIN": True,  # Prevent session fixation
        "BIND_TO_IP": True,  # Validate IP doesn't change
        "BIND_TO_USER_AGENT": False,  # Can cause issues with browser updates
    },
    # Password Validation
    "PASSWORD_VALIDATORS": {
        "MIN_LENGTH": 12,
        "COMPLEXITY": {
            "min_uppercase": 1,
            "min_lowercase": 1,
            "min_digits": 1,
            "min_special": 1,
        },
        "CHECK_BREACHED": True,
        "PREVENT_REUSE": 5,
        "FORBIDDEN_SUBSTRINGS": [
            "company",
            "name",
            "xpendit",
        ],
    },
    # Encrypted File Field Configuration
    "FILE_ENCRYPTION_KEY": config(
        "FILE_ENCRYPTION_KEY",
        default=None,  # Will generate one in development if not set
    ),
    "ENCRYPTED_FILES": {
        "ENABLED": True,
        "MAX_SIZE": 10 * 1024 * 1024,  # 10MB default
        "ALLOWED_EXTENSIONS": [
            ".pdf",
            ".docx",
            ".xlsx",
            ".jpg",
            ".png",
            ".txt",
            ".csv",
        ],
        "VALIDATE_MIME": True,
        # Configurable dangerous extensions
        "DANGEROUS_EXTENSIONS": [
            # Executables
            ".exe",
            ".dll",
            ".so",
            ".dylib",
            ".app",
            # Scripts
            ".bat",
            ".cmd",
            ".sh",
            ".ps1",
            ".vbs",
            ".js",
            ".jse",
            ".wsf",
            ".wsh",
            # System files
            ".com",
            ".scr",
            ".msi",
            ".jar",
            ".deb",
            ".rpm",
            ".dmg",
            # Code files that could be executed
            ".py",
            ".php",
            ".asp",
            ".aspx",
            ".jsp",
            ".cgi",
            # Office macros
            ".xlsm",
            ".docm",
            ".pptm",
            # Other potentially dangerous
            ".lnk",
            ".inf",
            ".reg",
            ".gadget",
        ],
        # Signed URLs Configuration
        "SIGNED_URLS": {
            "ENABLED": True,
            "DEFAULT_EXPIRY": 3600,  # 1 hour
            "BIND_TO_IP": False,  # Don't bind to IP by default
            "INCLUDE_PERMISSIONS": True,
            "DOWNLOAD_ENDPOINT": "/api/secure-download/",
        },
    },
}

# Apply secure defaults based on environment
from app.security.conf import apply_secure_defaults  # noqa: E402

# # Use relaxed preset for development, moderate for production
if DEBUG:
    apply_secure_defaults(globals(), preset="relaxed")
else:
    apply_secure_defaults(globals(), preset=DJANGO_SEC["RISK_PROFILE"])




# The apply_secure_defaults function will automatically add our security middleware
# to the MIDDLEWARE list, so no manual modification needed there

SECURITY_CONFIG = {
    "COMPLIANCE_STANDARD": "ISO27001",
    "AUDIT_LOG": {
        "ENABLED": True,
        "DECOUPLED_MODE": True,
        "HASH_CHAINING": True,
        "STORAGE_BACKEND": "auditory.audit.backends.tamper_evident.TamperEvidentPostgres",
        "PII_MASKING": "auditory.audit.policies.StrictMasking",
        "MODELS": [
            # WHITELIST MODE (opcional): Si esta lista NO está vacía, solo se auditarán estos modelos
            # Deja esta lista vacía [] para auditar TODOS los modelos automáticamente
            # Ejemplos:
            # "auth.User",           # Usuarios de Django
            # "auth.Group",          # Grupos de Django
            # "app.Modelo",          # Modelos de tu aplicación
        ],
        "MODELS_BLACKLIST": [
            # BLACKLIST: Modelos que NUNCA se auditarán (solo aplica cuando MODELS está vacío)
            # Los modelos de Django internos suelen ser seguros para excluir
            "contenttypes.contenttype",  # Tipos de contenido de Django
            "auth.permission",  # Permisos de Django (raramente cambian)
            "sessions.session",  # Sesiones (muy volátiles, poco valor de auditoría)
            "admin.logentry",  # Ya es un log de auditoría de Django
            "auditory.apirequestlog",  # API request logs (no auditar auditorías)
            # Agrega aquí otros modelos que no necesites auditar
        ],
        "RETENTION_DAYS": 90,
        "MAX_BODY_LENGTH": 8192,
    },
    "HTTP_SECURITY": {
        "ENABLED": True,
        "HSTS_SECONDS": 31536000,
        "CSP_ENFORCE": True,
        "X_FRAME_OPTIONS": "DENY",
    },
    # NEW: API Request Logging Configuration
    "API_REQUEST_LOG": {
        "ENABLED": True,
        "LOG_SUCCESSFUL_REQUESTS": True,  # Log 2xx responses
        "LOG_CLIENT_ERRORS": True,  # Log 4xx responses
        "LOG_SERVER_ERRORS": True,  # Log 5xx responses
        "EXCLUDE_PATHS": [
            "/admin/jsi18n/",  # Django admin i18n
            "/static/",  # Static files
            "/media/",  # Media files
            "/health/",  # Health check endpoint
            "/metrics/",  # Metrics endpoint
        ],
        "SAMPLING_RATE": 1.0,  # 1.0 = 100%, 0.1 = 10%
        "COLLECT_REQUEST_BODY": True,
        "COLLECT_RESPONSE_BODY_ON_ERROR": True,
        "MAX_BODY_SIZE": 10240,  # 10KB
        "ANONYMIZE_IPS": False,  # Set to True for GDPR compliance
        "RETENTION_DAYS": 180,  # 6 months for compliance
    },
}


# =============================================================================
# DATA PROTECTION CONFIGURATION (ISO27001 A.10.1 - Cryptographic Controls)
# =============================================================================

# Encryption Configuration
# Note: By default, encryption keys are derived from SECRET_KEY using PBKDF2
# For production, consider using dedicated encryption keys stored securely

# Optional: Provide a dedicated Fernet key (base64-encoded, 32 bytes)
# Generate with: from cryptography.fernet import Fernet; print(Fernet.generate_key())
# DATA_PROTECTION_KEY = None  # Uses SECRET_KEY if not set

# Optional: Custom salt for searchable index hashing
# DATA_PROTECTION_SEARCH_SALT = None  # Uses SECRET_KEY if not set

# Searchable Encryption Configuration
DATA_PROTECTION: dict[str, object] = {
    # N-gram configuration for searchable encryption
    'NGRAM_SIZE': 3,  # Size of n-grams for indexing (3 = trigrams)
    'MIN_SEARCH_LENGTH': 2,  # Minimum search term length

    # Key rotation support (future)
    'KEY_VERSION': 'v1',  # Current key version

    # Compliance
    'ENCRYPTION_ALGORITHM': 'Fernet (AES-128 CBC)',  # ISO27001 compliant
    'KEY_DERIVATION': 'PBKDF2-HMAC-SHA256',  # NIST recommended
}

# =============================================================================
# DJANGO-CRYPTO-FIELDS CONFIGURATION
# =============================================================================

# Key path for django-crypto-fields
# IMPORTANT: Must be OUTSIDE the project directory for security
# In development: uses /tmp/crypto_keys
# In production: set DJANGO_CRYPTO_FIELDS_KEY_PATH env var to a secure location
DJANGO_CRYPTO_FIELDS_KEY_PATH = Path(
    config(
        'DJANGO_CRYPTO_FIELDS_KEY_PATH',
        default='/tmp/crypto_keys' if DEBUG else str(BASE_DIR.parent / 'crypto_keys')
    )
)

if not DJANGO_CRYPTO_FIELDS_KEY_PATH.exists():
    DJANGO_CRYPTO_FIELDS_KEY_PATH.mkdir(parents=True, mode=0o700)

# Auto-create keys on first run
AUTO_CREATE_KEYS = True
