# Generated by Django 5.2.8 on 2025-11-23 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordhistory',
            name='user',
            field=models.ForeignKey(help_text='User whose password this was', on_delete=django.db.models.deletion.CASCADE, related_name='password_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciouslogin',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, help_text='Who reviewed this login', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_suspicious_logins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciouslogin',
            name='user',
            field=models.ForeignKey(help_text='User who logged in', on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_logins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passwordhistory',
            index=models.Index(fields=['user', '-created_at'], name='auth_securi_user_id_e08010_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouslogin',
            index=models.Index(fields=['-timestamp', 'user'], name='auth_securi_timesta_0367e2_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciouslogin',
            index=models.Index(fields=['reviewed', '-timestamp'], name='auth_securi_reviewe_f66a18_idx'),
        ),
    ]
