# Generated by Django 5.2.8 on 2025-11-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("app_label", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("object_pk", models.CharField(max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "create"),
                            ("update", "update"),
                            ("delete", "delete"),
                        ],
                        max_length=16,
                    ),
                ),
                ("snapshot", models.JSONField(default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("actor", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "actor_label",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "correlation_id",
                    models.CharField(blank=True, max_length=64, null=True),
                ),
                ("request_path", models.TextField(blank=True, null=True)),
                ("http_method", models.CharField(blank=True, max_length=8, null=True)),
                ("body", models.JSONField(blank=True, null=True)),
                ("hash_prev", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "hash_current",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["app_label", "model", "object_pk"],
                        name="auditory_au_app_lab_a81a2b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="auditory_au_timesta_d79452_idx"
                    ),
                ],
            },
        ),
    ]
