# Generated by Django 5.2.8 on 2025-11-22 21:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("auditory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="auditlogentry",
            options={
                "ordering": ["-timestamp"],
                "verbose_name": "Audit Log Entry",
                "verbose_name_plural": "Audit Log Entries",
            },
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="auditory_au_app_lab_0be680_idx",
            old_name="auditory_au_app_lab_a81a2b_idx",
        ),
        migrations.RenameIndex(
            model_name="auditlogentry",
            new_name="auditory_au_timesta_9cdfc3_idx",
            old_name="auditory_au_timesta_d79452_idx",
        ),
    ]
