# Generated by Django 5.2.8 on 2025-11-22 22:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditory", "0003_apirequestlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequestlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apirequestlog",
            name="user_agent",
            field=models.TextField(blank=True, null=True),
        ),
    ]
