# Generated by Django 5.2.8 on 2025-11-22 19:29

import django_crypto_fields.fields.encrypted_char_field
import django_crypto_fields.fields.encrypted_date_field
import django_crypto_fields.fields.encrypted_integer_field
import django_crypto_fields.fields.encrypted_text_field
from django.db import migrations, models

import data_protection.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoCryptoFieldsExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=100)),
                ('last_name', django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text=' (Encryption: RSA local)', max_length=100)),
                ('ssn', django_crypto_fields.fields.encrypted_char_field.EncryptedCharField(blank=True, help_text='SSN (encrypted, no pattern matching) (Encryption: RSA local)', max_length=71, null=True)),
                ('medical_history', django_crypto_fields.fields.encrypted_text_field.EncryptedTextField(blank=True, help_text='Medical history (encrypted) (Encryption: AES local)', max_length=71, null=True)),
                ('patient_id', django_crypto_fields.fields.encrypted_integer_field.EncryptedIntegerField(blank=True, help_text='Patient ID (encrypted) (Encryption: RSA local)', max_length=71)),
                ('date_of_birth', django_crypto_fields.fields.encrypted_date_field.EncryptedDateField(blank=True, help_text='DOB (encrypted) (Encryption: RSA local)', max_length=71)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Django Crypto Fields Example',
                'verbose_name_plural': 'Django Crypto Fields Examples',
                'db_table': 'data_protection_django_crypto',
            },
        ),
        migrations.CreateModel(
            name='SearchableDataExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', data_protection.fields.SearchableEncryptedTextField(blank=True, help_text='Email (encrypted, searchable with separate n-gram table) (Encryption: AES local)', max_length=71)),
                ('notes', data_protection.fields.SearchableEncryptedTextField(blank=True, help_text='Notes (encrypted, searchable with separate n-gram table) (Encryption: AES local)', max_length=71, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Searchable Data Example',
                'verbose_name_plural': 'Searchable Data Examples',
                'db_table': 'data_protection_searchable',
            },
        ),
    ]
